server:
  port: 7777

spring:
  application:
    name: zuul

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api
  routes:
    product:
      path: /product/**
      serviceId: product
    inventory:
      path: /inventory/**
      serviceId: inventory
    cart:
      path: /cart/**
      serviceId: cart
    user:
      path: /user/**
      serviceId: user

ribbon:
  ReadTimeout: 60000

token:
  secret: "n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf"
